/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AcompanharRouteImport } from './routes/acompanhar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as MeusPedidosRouteImport } from './routes/meus-pedidos'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SlugIndexRouteImport } from './routes/$slug.index'
import { Route as SlugAcompanharRouteImport } from './routes/$slug.acompanhar'
import { Route as SlugCarrinhoRouteImport } from './routes/$slug.carrinho'
import { Route as SlugCheckoutRouteImport } from './routes/$slug.checkout'
import { Route as SlugMembrosRouteImport } from './routes/$slug.membros'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCompletarCadastroRouteImport } from './routes/_authenticated/completar-cadastro'
import { Route as AuthenticatedEntregadorRouteImport } from './routes/_authenticated/entregador'
import { Route as AuthenticatedEscolherPerfilRouteImport } from './routes/_authenticated/escolher-perfil'
import { Route as AuthenticatedGarcomRouteImport } from './routes/_authenticated/garcom'
import { Route as AuthenticatedKdsRouteImport } from './routes/_authenticated/kds'
import { Route as AuthenticatedMinhaContaRouteImport } from './routes/_authenticated/minha-conta'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPdvRouteImport } from './routes/_authenticated/pdv'
import { Route as AgendamentoTokenRouteImport } from './routes/agendamento.$token'
import { Route as EncomendaTokenRouteImport } from './routes/encomenda.$token'
import { Route as EntregaTokenRouteImport } from './routes/entrega.$token'
import { Route as LojaSplatRouteImport } from './routes/loja.$'
import { Route as MesaTokenRouteImport } from './routes/mesa.$token'
import { Route as OrcamentoTokenRouteImport } from './routes/orcamento.$token'
import { Route as SlugCheckoutAgendamentoRouteImport } from './routes/$slug.checkout_.agendamento'
import { Route as SlugCheckoutDigitalRouteImport } from './routes/$slug.checkout_.digital'
import { Route as SlugCheckoutLojaRouteImport } from './routes/$slug.checkout_.loja'
import { Route as AuthenticatedConviteTokenRouteImport } from './routes/_authenticated/convite.$token'
import { Route as AuthenticatedEntregadorStatusRouteImport } from './routes/_authenticated/entregador_.status'
import { Route as AuthenticatedPainelIndexRouteImport } from './routes/_authenticated/painel.index'
import { Route as AuthenticatedPainelAgendamentosRouteImport } from './routes/_authenticated/painel.agendamentos'
import { Route as AuthenticatedPainelAssinaturaRouteImport } from './routes/_authenticated/painel.assinatura'
import { Route as AuthenticatedPainelAvaliacoesRouteImport } from './routes/_authenticated/painel.avaliacoes'
import { Route as AuthenticatedPainelClientesRouteImport } from './routes/_authenticated/painel.clientes'
import { Route as AuthenticatedPainelCobrancasRouteImport } from './routes/_authenticated/painel.cobrancas'
import { Route as AuthenticatedPainelConfiguracoesRouteImport } from './routes/_authenticated/painel.configuracoes'
import { Route as AuthenticatedPainelDigitaisRouteImport } from './routes/_authenticated/painel.digitais'
import { Route as AuthenticatedPainelEncomendasRouteImport } from './routes/_authenticated/painel.encomendas'
import { Route as AuthenticatedPainelEntregadoresRouteImport } from './routes/_authenticated/painel.entregadores'
import { Route as AuthenticatedPainelEntregasRouteImport } from './routes/_authenticated/painel.entregas'
import { Route as AuthenticatedPainelEquipeRouteImport } from './routes/_authenticated/painel.equipe'
import { Route as AuthenticatedPainelEstoqueRouteImport } from './routes/_authenticated/painel.estoque'
import { Route as AuthenticatedPainelFidelidadeRouteImport } from './routes/_authenticated/painel.fidelidade'
import { Route as AuthenticatedPainelFreteRouteImport } from './routes/_authenticated/painel.frete'
import { Route as AuthenticatedPainelImpressaoRouteImport } from './routes/_authenticated/painel.impressao'
import { Route as AuthenticatedPainelIntegracoesRouteImport } from './routes/_authenticated/painel.integracoes'
import { Route as AuthenticatedPainelKdsRouteImport } from './routes/_authenticated/painel.kds'
import { Route as AuthenticatedPainelPagamentosRouteImport } from './routes/_authenticated/painel.pagamentos'
import { Route as AuthenticatedPainelPdvRouteImport } from './routes/_authenticated/painel.pdv'
import { Route as AuthenticatedPainelPedidosRouteImport } from './routes/_authenticated/painel.pedidos'
import { Route as AuthenticatedPainelPersonalizarRouteImport } from './routes/_authenticated/painel.personalizar'
import { Route as AuthenticatedPainelPrivacidadeRouteImport } from './routes/_authenticated/painel.privacidade'
import { Route as AuthenticatedPainelProdutosRouteImport } from './routes/_authenticated/painel.produtos'
import { Route as AuthenticatedPainelPromocoesRouteImport } from './routes/_authenticated/painel.promocoes'
import { Route as AuthenticatedPainelRelatoriosRouteImport } from './routes/_authenticated/painel.relatorios'
import { Route as AuthenticatedPainelSalaoRouteImport } from './routes/_authenticated/painel.salao'
import { Route as AuthenticatedPainelSuporteRouteImport } from './routes/_authenticated/painel.suporte'
import { Route as AuthenticatedPainelWhatsappRouteImport } from './routes/_authenticated/painel.whatsapp'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as ApiPublicAgendaLembretesRouteImport } from './routes/api/public/agenda/lembretes'
import { Route as ApiPublicAssinaturasCobrancasRouteImport } from './routes/api/public/assinaturas/cobrancas'
import { Route as ApiPublicAssinaturasPedidosRouteImport } from './routes/api/public/assinaturas/pedidos'
import { Route as ApiPublicCarrinhoLembretesRouteImport } from './routes/api/public/carrinho/lembretes'
import { Route as ApiPublicCashbackExpiracaoRouteImport } from './routes/api/public/cashback/expiracao'
import { Route as ApiPublicEncomendasLembretesRouteImport } from './routes/api/public/encomendas/lembretes'
import { Route as ApiPublicEvolutionInstanceKeyRouteImport } from './routes/api/public/evolution/$instanceKey'
import { Route as ApiPublicIntegracoesRetentativasRouteImport } from './routes/api/public/integracoes/retentativas'
import { Route as ApiPublicNotificacoesPushRouteImport } from './routes/api/public/notificacoes/push'
import { Route as ApiPublicPagamentosProviderRouteImport } from './routes/api/public/pagamentos/$provider'
import { Route as ApiPublicV1SplatRouteImport } from './routes/api/public/v1/$'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as ApiPublicIntegracoesKindStoreIdRouteImport } from './routes/api/public/integracoes/$kind.$storeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanharRoute = AcompanharRouteImport.update({
  id: '/acompanhar',
  path: '/acompanhar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusPedidosRoute = MeusPedidosRouteImport.update({
  id: '/meus-pedidos',
  path: '/meus-pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugAcompanharRoute = SlugAcompanharRouteImport.update({
  id: '/$slug/acompanhar',
  path: '/$slug/acompanhar',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugCarrinhoRoute = SlugCarrinhoRouteImport.update({
  id: '/$slug/carrinho',
  path: '/$slug/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugCheckoutRoute = SlugCheckoutRouteImport.update({
  id: '/$slug/checkout',
  path: '/$slug/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugMembrosRoute = SlugMembrosRouteImport.update({
  id: '/$slug/membros',
  path: '/$slug/membros',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompletarCadastroRoute =
  AuthenticatedCompletarCadastroRouteImport.update({
    id: '/completar-cadastro',
    path: '/completar-cadastro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntregadorRoute = AuthenticatedEntregadorRouteImport.update({
  id: '/entregador',
  path: '/entregador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEscolherPerfilRoute =
  AuthenticatedEscolherPerfilRouteImport.update({
    id: '/escolher-perfil',
    path: '/escolher-perfil',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGarcomRoute = AuthenticatedGarcomRouteImport.update({
  id: '/garcom',
  path: '/garcom',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKdsRoute = AuthenticatedKdsRouteImport.update({
  id: '/kds',
  path: '/kds',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinhaContaRoute = AuthenticatedMinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPdvRoute = AuthenticatedPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AgendamentoTokenRoute = AgendamentoTokenRouteImport.update({
  id: '/agendamento/$token',
  path: '/agendamento/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EncomendaTokenRoute = EncomendaTokenRouteImport.update({
  id: '/encomenda/$token',
  path: '/encomenda/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregaTokenRoute = EntregaTokenRouteImport.update({
  id: '/entrega/$token',
  path: '/entrega/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaSplatRoute = LojaSplatRouteImport.update({
  id: '/loja/$',
  path: '/loja/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MesaTokenRoute = MesaTokenRouteImport.update({
  id: '/mesa/$token',
  path: '/mesa/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoTokenRoute = OrcamentoTokenRouteImport.update({
  id: '/orcamento/$token',
  path: '/orcamento/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugCheckoutAgendamentoRoute = SlugCheckoutAgendamentoRouteImport.update({
  id: '/$slug/checkout_/agendamento',
  path: '/$slug/checkout/agendamento',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugCheckoutDigitalRoute = SlugCheckoutDigitalRouteImport.update({
  id: '/$slug/checkout_/digital',
  path: '/$slug/checkout/digital',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugCheckoutLojaRoute = SlugCheckoutLojaRouteImport.update({
  id: '/$slug/checkout_/loja',
  path: '/$slug/checkout/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConviteTokenRoute =
  AuthenticatedConviteTokenRouteImport.update({
    id: '/convite/$token',
    path: '/convite/$token',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntregadorStatusRoute =
  AuthenticatedEntregadorStatusRouteImport.update({
    id: '/entregador_/status',
    path: '/entregador/status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelIndexRoute =
  AuthenticatedPainelIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelAgendamentosRoute =
  AuthenticatedPainelAgendamentosRouteImport.update({
    id: '/agendamentos',
    path: '/agendamentos',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelAssinaturaRoute =
  AuthenticatedPainelAssinaturaRouteImport.update({
    id: '/assinatura',
    path: '/assinatura',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelAvaliacoesRoute =
  AuthenticatedPainelAvaliacoesRouteImport.update({
    id: '/avaliacoes',
    path: '/avaliacoes',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelClientesRoute =
  AuthenticatedPainelClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelCobrancasRoute =
  AuthenticatedPainelCobrancasRouteImport.update({
    id: '/cobrancas',
    path: '/cobrancas',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelConfiguracoesRoute =
  AuthenticatedPainelConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelDigitaisRoute =
  AuthenticatedPainelDigitaisRouteImport.update({
    id: '/digitais',
    path: '/digitais',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelEncomendasRoute =
  AuthenticatedPainelEncomendasRouteImport.update({
    id: '/encomendas',
    path: '/encomendas',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelEntregadoresRoute =
  AuthenticatedPainelEntregadoresRouteImport.update({
    id: '/entregadores',
    path: '/entregadores',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelEntregasRoute =
  AuthenticatedPainelEntregasRouteImport.update({
    id: '/entregas',
    path: '/entregas',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelEquipeRoute =
  AuthenticatedPainelEquipeRouteImport.update({
    id: '/equipe',
    path: '/equipe',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelEstoqueRoute =
  AuthenticatedPainelEstoqueRouteImport.update({
    id: '/estoque',
    path: '/estoque',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelFidelidadeRoute =
  AuthenticatedPainelFidelidadeRouteImport.update({
    id: '/fidelidade',
    path: '/fidelidade',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelFreteRoute =
  AuthenticatedPainelFreteRouteImport.update({
    id: '/frete',
    path: '/frete',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelImpressaoRoute =
  AuthenticatedPainelImpressaoRouteImport.update({
    id: '/impressao',
    path: '/impressao',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelIntegracoesRoute =
  AuthenticatedPainelIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelKdsRoute = AuthenticatedPainelKdsRouteImport.update({
  id: '/kds',
  path: '/kds',
  getParentRoute: () => AuthenticatedPainelRoute,
} as any)
const AuthenticatedPainelPagamentosRoute =
  AuthenticatedPainelPagamentosRouteImport.update({
    id: '/pagamentos',
    path: '/pagamentos',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelPdvRoute = AuthenticatedPainelPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AuthenticatedPainelRoute,
} as any)
const AuthenticatedPainelPedidosRoute =
  AuthenticatedPainelPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelPersonalizarRoute =
  AuthenticatedPainelPersonalizarRouteImport.update({
    id: '/personalizar',
    path: '/personalizar',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelPrivacidadeRoute =
  AuthenticatedPainelPrivacidadeRouteImport.update({
    id: '/privacidade',
    path: '/privacidade',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelProdutosRoute =
  AuthenticatedPainelProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelPromocoesRoute =
  AuthenticatedPainelPromocoesRouteImport.update({
    id: '/promocoes',
    path: '/promocoes',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelRelatoriosRoute =
  AuthenticatedPainelRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelSalaoRoute =
  AuthenticatedPainelSalaoRouteImport.update({
    id: '/salao',
    path: '/salao',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelSuporteRoute =
  AuthenticatedPainelSuporteRouteImport.update({
    id: '/suporte',
    path: '/suporte',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelWhatsappRoute =
  AuthenticatedPainelWhatsappRouteImport.update({
    id: '/whatsapp',
    path: '/whatsapp',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgendaLembretesRoute =
  ApiPublicAgendaLembretesRouteImport.update({
    id: '/api/public/agenda/lembretes',
    path: '/api/public/agenda/lembretes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAssinaturasCobrancasRoute =
  ApiPublicAssinaturasCobrancasRouteImport.update({
    id: '/api/public/assinaturas/cobrancas',
    path: '/api/public/assinaturas/cobrancas',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAssinaturasPedidosRoute =
  ApiPublicAssinaturasPedidosRouteImport.update({
    id: '/api/public/assinaturas/pedidos',
    path: '/api/public/assinaturas/pedidos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCarrinhoLembretesRoute =
  ApiPublicCarrinhoLembretesRouteImport.update({
    id: '/api/public/carrinho/lembretes',
    path: '/api/public/carrinho/lembretes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCashbackExpiracaoRoute =
  ApiPublicCashbackExpiracaoRouteImport.update({
    id: '/api/public/cashback/expiracao',
    path: '/api/public/cashback/expiracao',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEncomendasLembretesRoute =
  ApiPublicEncomendasLembretesRouteImport.update({
    id: '/api/public/encomendas/lembretes',
    path: '/api/public/encomendas/lembretes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEvolutionInstanceKeyRoute =
  ApiPublicEvolutionInstanceKeyRouteImport.update({
    id: '/api/public/evolution/$instanceKey',
    path: '/api/public/evolution/$instanceKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIntegracoesRetentativasRoute =
  ApiPublicIntegracoesRetentativasRouteImport.update({
    id: '/api/public/integracoes/retentativas',
    path: '/api/public/integracoes/retentativas',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNotificacoesPushRoute =
  ApiPublicNotificacoesPushRouteImport.update({
    id: '/api/public/notificacoes/push',
    path: '/api/public/notificacoes/push',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPagamentosProviderRoute =
  ApiPublicPagamentosProviderRouteImport.update({
    id: '/api/public/pagamentos/$provider',
    path: '/api/public/pagamentos/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1SplatRoute = ApiPublicV1SplatRouteImport.update({
  id: '/api/public/v1/$',
  path: '/api/public/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIntegracoesKindStoreIdRoute =
  ApiPublicIntegracoesKindStoreIdRouteImport.update({
    id: '/api/public/integracoes/$kind/$storeId',
    path: '/api/public/integracoes/$kind/$storeId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acompanhar': typeof AcompanharRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/$slug/acompanhar': typeof SlugAcompanharRoute
  '/$slug/carrinho': typeof SlugCarrinhoRoute
  '/$slug/checkout': typeof SlugCheckoutRoute
  '/$slug/membros': typeof SlugMembrosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/completar-cadastro': typeof AuthenticatedCompletarCadastroRoute
  '/entregador': typeof AuthenticatedEntregadorRoute
  '/escolher-perfil': typeof AuthenticatedEscolherPerfilRoute
  '/garcom': typeof AuthenticatedGarcomRoute
  '/kds': typeof AuthenticatedKdsRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/painel': typeof AuthenticatedPainelRouteWithChildren
  '/pdv': typeof AuthenticatedPdvRoute
  '/agendamento/$token': typeof AgendamentoTokenRoute
  '/encomenda/$token': typeof EncomendaTokenRoute
  '/entrega/$token': typeof EntregaTokenRoute
  '/loja/$': typeof LojaSplatRoute
  '/mesa/$token': typeof MesaTokenRoute
  '/orcamento/$token': typeof OrcamentoTokenRoute
  '/$slug/': typeof SlugIndexRoute
  '/$slug/checkout/agendamento': typeof SlugCheckoutAgendamentoRoute
  '/$slug/checkout/digital': typeof SlugCheckoutDigitalRoute
  '/$slug/checkout/loja': typeof SlugCheckoutLojaRoute
  '/convite/$token': typeof AuthenticatedConviteTokenRoute
  '/entregador/status': typeof AuthenticatedEntregadorStatusRoute
  '/painel/agendamentos': typeof AuthenticatedPainelAgendamentosRoute
  '/painel/assinatura': typeof AuthenticatedPainelAssinaturaRoute
  '/painel/avaliacoes': typeof AuthenticatedPainelAvaliacoesRoute
  '/painel/clientes': typeof AuthenticatedPainelClientesRoute
  '/painel/cobrancas': typeof AuthenticatedPainelCobrancasRoute
  '/painel/configuracoes': typeof AuthenticatedPainelConfiguracoesRoute
  '/painel/digitais': typeof AuthenticatedPainelDigitaisRoute
  '/painel/encomendas': typeof AuthenticatedPainelEncomendasRoute
  '/painel/entregadores': typeof AuthenticatedPainelEntregadoresRoute
  '/painel/entregas': typeof AuthenticatedPainelEntregasRoute
  '/painel/equipe': typeof AuthenticatedPainelEquipeRoute
  '/painel/estoque': typeof AuthenticatedPainelEstoqueRoute
  '/painel/fidelidade': typeof AuthenticatedPainelFidelidadeRoute
  '/painel/frete': typeof AuthenticatedPainelFreteRoute
  '/painel/impressao': typeof AuthenticatedPainelImpressaoRoute
  '/painel/integracoes': typeof AuthenticatedPainelIntegracoesRoute
  '/painel/kds': typeof AuthenticatedPainelKdsRoute
  '/painel/pagamentos': typeof AuthenticatedPainelPagamentosRoute
  '/painel/pdv': typeof AuthenticatedPainelPdvRoute
  '/painel/pedidos': typeof AuthenticatedPainelPedidosRoute
  '/painel/personalizar': typeof AuthenticatedPainelPersonalizarRoute
  '/painel/privacidade': typeof AuthenticatedPainelPrivacidadeRoute
  '/painel/produtos': typeof AuthenticatedPainelProdutosRoute
  '/painel/promocoes': typeof AuthenticatedPainelPromocoesRoute
  '/painel/relatorios': typeof AuthenticatedPainelRelatoriosRoute
  '/painel/salao': typeof AuthenticatedPainelSalaoRoute
  '/painel/suporte': typeof AuthenticatedPainelSuporteRoute
  '/painel/whatsapp': typeof AuthenticatedPainelWhatsappRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/painel/': typeof AuthenticatedPainelIndexRoute
  '/api/public/agenda/lembretes': typeof ApiPublicAgendaLembretesRoute
  '/api/public/assinaturas/cobrancas': typeof ApiPublicAssinaturasCobrancasRoute
  '/api/public/assinaturas/pedidos': typeof ApiPublicAssinaturasPedidosRoute
  '/api/public/carrinho/lembretes': typeof ApiPublicCarrinhoLembretesRoute
  '/api/public/cashback/expiracao': typeof ApiPublicCashbackExpiracaoRoute
  '/api/public/encomendas/lembretes': typeof ApiPublicEncomendasLembretesRoute
  '/api/public/evolution/$instanceKey': typeof ApiPublicEvolutionInstanceKeyRoute
  '/api/public/integracoes/retentativas': typeof ApiPublicIntegracoesRetentativasRoute
  '/api/public/notificacoes/push': typeof ApiPublicNotificacoesPushRoute
  '/api/public/pagamentos/$provider': typeof ApiPublicPagamentosProviderRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/api/public/integracoes/$kind/$storeId': typeof ApiPublicIntegracoesKindStoreIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acompanhar': typeof AcompanharRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/$slug/acompanhar': typeof SlugAcompanharRoute
  '/$slug/carrinho': typeof SlugCarrinhoRoute
  '/$slug/checkout': typeof SlugCheckoutRoute
  '/$slug/membros': typeof SlugMembrosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/completar-cadastro': typeof AuthenticatedCompletarCadastroRoute
  '/entregador': typeof AuthenticatedEntregadorRoute
  '/escolher-perfil': typeof AuthenticatedEscolherPerfilRoute
  '/garcom': typeof AuthenticatedGarcomRoute
  '/kds': typeof AuthenticatedKdsRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pdv': typeof AuthenticatedPdvRoute
  '/agendamento/$token': typeof AgendamentoTokenRoute
  '/encomenda/$token': typeof EncomendaTokenRoute
  '/entrega/$token': typeof EntregaTokenRoute
  '/loja/$': typeof LojaSplatRoute
  '/mesa/$token': typeof MesaTokenRoute
  '/orcamento/$token': typeof OrcamentoTokenRoute
  '/$slug': typeof SlugIndexRoute
  '/$slug/checkout/agendamento': typeof SlugCheckoutAgendamentoRoute
  '/$slug/checkout/digital': typeof SlugCheckoutDigitalRoute
  '/$slug/checkout/loja': typeof SlugCheckoutLojaRoute
  '/convite/$token': typeof AuthenticatedConviteTokenRoute
  '/entregador/status': typeof AuthenticatedEntregadorStatusRoute
  '/painel/agendamentos': typeof AuthenticatedPainelAgendamentosRoute
  '/painel/assinatura': typeof AuthenticatedPainelAssinaturaRoute
  '/painel/avaliacoes': typeof AuthenticatedPainelAvaliacoesRoute
  '/painel/clientes': typeof AuthenticatedPainelClientesRoute
  '/painel/cobrancas': typeof AuthenticatedPainelCobrancasRoute
  '/painel/configuracoes': typeof AuthenticatedPainelConfiguracoesRoute
  '/painel/digitais': typeof AuthenticatedPainelDigitaisRoute
  '/painel/encomendas': typeof AuthenticatedPainelEncomendasRoute
  '/painel/entregadores': typeof AuthenticatedPainelEntregadoresRoute
  '/painel/entregas': typeof AuthenticatedPainelEntregasRoute
  '/painel/equipe': typeof AuthenticatedPainelEquipeRoute
  '/painel/estoque': typeof AuthenticatedPainelEstoqueRoute
  '/painel/fidelidade': typeof AuthenticatedPainelFidelidadeRoute
  '/painel/frete': typeof AuthenticatedPainelFreteRoute
  '/painel/impressao': typeof AuthenticatedPainelImpressaoRoute
  '/painel/integracoes': typeof AuthenticatedPainelIntegracoesRoute
  '/painel/kds': typeof AuthenticatedPainelKdsRoute
  '/painel/pagamentos': typeof AuthenticatedPainelPagamentosRoute
  '/painel/pdv': typeof AuthenticatedPainelPdvRoute
  '/painel/pedidos': typeof AuthenticatedPainelPedidosRoute
  '/painel/personalizar': typeof AuthenticatedPainelPersonalizarRoute
  '/painel/privacidade': typeof AuthenticatedPainelPrivacidadeRoute
  '/painel/produtos': typeof AuthenticatedPainelProdutosRoute
  '/painel/promocoes': typeof AuthenticatedPainelPromocoesRoute
  '/painel/relatorios': typeof AuthenticatedPainelRelatoriosRoute
  '/painel/salao': typeof AuthenticatedPainelSalaoRoute
  '/painel/suporte': typeof AuthenticatedPainelSuporteRoute
  '/painel/whatsapp': typeof AuthenticatedPainelWhatsappRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/painel': typeof AuthenticatedPainelIndexRoute
  '/api/public/agenda/lembretes': typeof ApiPublicAgendaLembretesRoute
  '/api/public/assinaturas/cobrancas': typeof ApiPublicAssinaturasCobrancasRoute
  '/api/public/assinaturas/pedidos': typeof ApiPublicAssinaturasPedidosRoute
  '/api/public/carrinho/lembretes': typeof ApiPublicCarrinhoLembretesRoute
  '/api/public/cashback/expiracao': typeof ApiPublicCashbackExpiracaoRoute
  '/api/public/encomendas/lembretes': typeof ApiPublicEncomendasLembretesRoute
  '/api/public/evolution/$instanceKey': typeof ApiPublicEvolutionInstanceKeyRoute
  '/api/public/integracoes/retentativas': typeof ApiPublicIntegracoesRetentativasRoute
  '/api/public/notificacoes/push': typeof ApiPublicNotificacoesPushRoute
  '/api/public/pagamentos/$provider': typeof ApiPublicPagamentosProviderRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/api/public/integracoes/$kind/$storeId': typeof ApiPublicIntegracoesKindStoreIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/acompanhar': typeof AcompanharRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/$slug/acompanhar': typeof SlugAcompanharRoute
  '/$slug/carrinho': typeof SlugCarrinhoRoute
  '/$slug/checkout': typeof SlugCheckoutRoute
  '/$slug/membros': typeof SlugMembrosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/completar-cadastro': typeof AuthenticatedCompletarCadastroRoute
  '/_authenticated/entregador': typeof AuthenticatedEntregadorRoute
  '/_authenticated/escolher-perfil': typeof AuthenticatedEscolherPerfilRoute
  '/_authenticated/garcom': typeof AuthenticatedGarcomRoute
  '/_authenticated/kds': typeof AuthenticatedKdsRoute
  '/_authenticated/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRouteWithChildren
  '/_authenticated/pdv': typeof AuthenticatedPdvRoute
  '/agendamento/$token': typeof AgendamentoTokenRoute
  '/encomenda/$token': typeof EncomendaTokenRoute
  '/entrega/$token': typeof EntregaTokenRoute
  '/loja/$': typeof LojaSplatRoute
  '/mesa/$token': typeof MesaTokenRoute
  '/orcamento/$token': typeof OrcamentoTokenRoute
  '/$slug/': typeof SlugIndexRoute
  '/$slug/checkout_/agendamento': typeof SlugCheckoutAgendamentoRoute
  '/$slug/checkout_/digital': typeof SlugCheckoutDigitalRoute
  '/$slug/checkout_/loja': typeof SlugCheckoutLojaRoute
  '/_authenticated/convite/$token': typeof AuthenticatedConviteTokenRoute
  '/_authenticated/entregador_/status': typeof AuthenticatedEntregadorStatusRoute
  '/_authenticated/painel/agendamentos': typeof AuthenticatedPainelAgendamentosRoute
  '/_authenticated/painel/assinatura': typeof AuthenticatedPainelAssinaturaRoute
  '/_authenticated/painel/avaliacoes': typeof AuthenticatedPainelAvaliacoesRoute
  '/_authenticated/painel/clientes': typeof AuthenticatedPainelClientesRoute
  '/_authenticated/painel/cobrancas': typeof AuthenticatedPainelCobrancasRoute
  '/_authenticated/painel/configuracoes': typeof AuthenticatedPainelConfiguracoesRoute
  '/_authenticated/painel/digitais': typeof AuthenticatedPainelDigitaisRoute
  '/_authenticated/painel/encomendas': typeof AuthenticatedPainelEncomendasRoute
  '/_authenticated/painel/entregadores': typeof AuthenticatedPainelEntregadoresRoute
  '/_authenticated/painel/entregas': typeof AuthenticatedPainelEntregasRoute
  '/_authenticated/painel/equipe': typeof AuthenticatedPainelEquipeRoute
  '/_authenticated/painel/estoque': typeof AuthenticatedPainelEstoqueRoute
  '/_authenticated/painel/fidelidade': typeof AuthenticatedPainelFidelidadeRoute
  '/_authenticated/painel/frete': typeof AuthenticatedPainelFreteRoute
  '/_authenticated/painel/impressao': typeof AuthenticatedPainelImpressaoRoute
  '/_authenticated/painel/integracoes': typeof AuthenticatedPainelIntegracoesRoute
  '/_authenticated/painel/kds': typeof AuthenticatedPainelKdsRoute
  '/_authenticated/painel/pagamentos': typeof AuthenticatedPainelPagamentosRoute
  '/_authenticated/painel/pdv': typeof AuthenticatedPainelPdvRoute
  '/_authenticated/painel/pedidos': typeof AuthenticatedPainelPedidosRoute
  '/_authenticated/painel/personalizar': typeof AuthenticatedPainelPersonalizarRoute
  '/_authenticated/painel/privacidade': typeof AuthenticatedPainelPrivacidadeRoute
  '/_authenticated/painel/produtos': typeof AuthenticatedPainelProdutosRoute
  '/_authenticated/painel/promocoes': typeof AuthenticatedPainelPromocoesRoute
  '/_authenticated/painel/relatorios': typeof AuthenticatedPainelRelatoriosRoute
  '/_authenticated/painel/salao': typeof AuthenticatedPainelSalaoRoute
  '/_authenticated/painel/suporte': typeof AuthenticatedPainelSuporteRoute
  '/_authenticated/painel/whatsapp': typeof AuthenticatedPainelWhatsappRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/_authenticated/painel/': typeof AuthenticatedPainelIndexRoute
  '/api/public/agenda/lembretes': typeof ApiPublicAgendaLembretesRoute
  '/api/public/assinaturas/cobrancas': typeof ApiPublicAssinaturasCobrancasRoute
  '/api/public/assinaturas/pedidos': typeof ApiPublicAssinaturasPedidosRoute
  '/api/public/carrinho/lembretes': typeof ApiPublicCarrinhoLembretesRoute
  '/api/public/cashback/expiracao': typeof ApiPublicCashbackExpiracaoRoute
  '/api/public/encomendas/lembretes': typeof ApiPublicEncomendasLembretesRoute
  '/api/public/evolution/$instanceKey': typeof ApiPublicEvolutionInstanceKeyRoute
  '/api/public/integracoes/retentativas': typeof ApiPublicIntegracoesRetentativasRoute
  '/api/public/notificacoes/push': typeof ApiPublicNotificacoesPushRoute
  '/api/public/pagamentos/$provider': typeof ApiPublicPagamentosProviderRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/api/public/integracoes/$kind/$storeId': typeof ApiPublicIntegracoesKindStoreIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acompanhar'
    | '/auth'
    | '/cookies'
    | '/meus-pedidos'
    | '/planos'
    | '/privacidade'
    | '/redefinir-senha'
    | '/termos'
    | '/$slug/acompanhar'
    | '/$slug/carrinho'
    | '/$slug/checkout'
    | '/$slug/membros'
    | '/admin'
    | '/completar-cadastro'
    | '/entregador'
    | '/escolher-perfil'
    | '/garcom'
    | '/kds'
    | '/minha-conta'
    | '/onboarding'
    | '/painel'
    | '/pdv'
    | '/agendamento/$token'
    | '/encomenda/$token'
    | '/entrega/$token'
    | '/loja/$'
    | '/mesa/$token'
    | '/orcamento/$token'
    | '/$slug/'
    | '/$slug/checkout/agendamento'
    | '/$slug/checkout/digital'
    | '/$slug/checkout/loja'
    | '/convite/$token'
    | '/entregador/status'
    | '/painel/agendamentos'
    | '/painel/assinatura'
    | '/painel/avaliacoes'
    | '/painel/clientes'
    | '/painel/cobrancas'
    | '/painel/configuracoes'
    | '/painel/digitais'
    | '/painel/encomendas'
    | '/painel/entregadores'
    | '/painel/entregas'
    | '/painel/equipe'
    | '/painel/estoque'
    | '/painel/fidelidade'
    | '/painel/frete'
    | '/painel/impressao'
    | '/painel/integracoes'
    | '/painel/kds'
    | '/painel/pagamentos'
    | '/painel/pdv'
    | '/painel/pedidos'
    | '/painel/personalizar'
    | '/painel/privacidade'
    | '/painel/produtos'
    | '/painel/promocoes'
    | '/painel/relatorios'
    | '/painel/salao'
    | '/painel/suporte'
    | '/painel/whatsapp'
    | '/api/v1/$'
    | '/painel/'
    | '/api/public/agenda/lembretes'
    | '/api/public/assinaturas/cobrancas'
    | '/api/public/assinaturas/pedidos'
    | '/api/public/carrinho/lembretes'
    | '/api/public/cashback/expiracao'
    | '/api/public/encomendas/lembretes'
    | '/api/public/evolution/$instanceKey'
    | '/api/public/integracoes/retentativas'
    | '/api/public/notificacoes/push'
    | '/api/public/pagamentos/$provider'
    | '/api/public/v1/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/api/public/integracoes/$kind/$storeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acompanhar'
    | '/auth'
    | '/cookies'
    | '/meus-pedidos'
    | '/planos'
    | '/privacidade'
    | '/redefinir-senha'
    | '/termos'
    | '/$slug/acompanhar'
    | '/$slug/carrinho'
    | '/$slug/checkout'
    | '/$slug/membros'
    | '/admin'
    | '/completar-cadastro'
    | '/entregador'
    | '/escolher-perfil'
    | '/garcom'
    | '/kds'
    | '/minha-conta'
    | '/onboarding'
    | '/pdv'
    | '/agendamento/$token'
    | '/encomenda/$token'
    | '/entrega/$token'
    | '/loja/$'
    | '/mesa/$token'
    | '/orcamento/$token'
    | '/$slug'
    | '/$slug/checkout/agendamento'
    | '/$slug/checkout/digital'
    | '/$slug/checkout/loja'
    | '/convite/$token'
    | '/entregador/status'
    | '/painel/agendamentos'
    | '/painel/assinatura'
    | '/painel/avaliacoes'
    | '/painel/clientes'
    | '/painel/cobrancas'
    | '/painel/configuracoes'
    | '/painel/digitais'
    | '/painel/encomendas'
    | '/painel/entregadores'
    | '/painel/entregas'
    | '/painel/equipe'
    | '/painel/estoque'
    | '/painel/fidelidade'
    | '/painel/frete'
    | '/painel/impressao'
    | '/painel/integracoes'
    | '/painel/kds'
    | '/painel/pagamentos'
    | '/painel/pdv'
    | '/painel/pedidos'
    | '/painel/personalizar'
    | '/painel/privacidade'
    | '/painel/produtos'
    | '/painel/promocoes'
    | '/painel/relatorios'
    | '/painel/salao'
    | '/painel/suporte'
    | '/painel/whatsapp'
    | '/api/v1/$'
    | '/painel'
    | '/api/public/agenda/lembretes'
    | '/api/public/assinaturas/cobrancas'
    | '/api/public/assinaturas/pedidos'
    | '/api/public/carrinho/lembretes'
    | '/api/public/cashback/expiracao'
    | '/api/public/encomendas/lembretes'
    | '/api/public/evolution/$instanceKey'
    | '/api/public/integracoes/retentativas'
    | '/api/public/notificacoes/push'
    | '/api/public/pagamentos/$provider'
    | '/api/public/v1/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/api/public/integracoes/$kind/$storeId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/acompanhar'
    | '/auth'
    | '/cookies'
    | '/meus-pedidos'
    | '/planos'
    | '/privacidade'
    | '/redefinir-senha'
    | '/termos'
    | '/$slug/acompanhar'
    | '/$slug/carrinho'
    | '/$slug/checkout'
    | '/$slug/membros'
    | '/_authenticated/admin'
    | '/_authenticated/completar-cadastro'
    | '/_authenticated/entregador'
    | '/_authenticated/escolher-perfil'
    | '/_authenticated/garcom'
    | '/_authenticated/kds'
    | '/_authenticated/minha-conta'
    | '/_authenticated/onboarding'
    | '/_authenticated/painel'
    | '/_authenticated/pdv'
    | '/agendamento/$token'
    | '/encomenda/$token'
    | '/entrega/$token'
    | '/loja/$'
    | '/mesa/$token'
    | '/orcamento/$token'
    | '/$slug/'
    | '/$slug/checkout_/agendamento'
    | '/$slug/checkout_/digital'
    | '/$slug/checkout_/loja'
    | '/_authenticated/convite/$token'
    | '/_authenticated/entregador_/status'
    | '/_authenticated/painel/agendamentos'
    | '/_authenticated/painel/assinatura'
    | '/_authenticated/painel/avaliacoes'
    | '/_authenticated/painel/clientes'
    | '/_authenticated/painel/cobrancas'
    | '/_authenticated/painel/configuracoes'
    | '/_authenticated/painel/digitais'
    | '/_authenticated/painel/encomendas'
    | '/_authenticated/painel/entregadores'
    | '/_authenticated/painel/entregas'
    | '/_authenticated/painel/equipe'
    | '/_authenticated/painel/estoque'
    | '/_authenticated/painel/fidelidade'
    | '/_authenticated/painel/frete'
    | '/_authenticated/painel/impressao'
    | '/_authenticated/painel/integracoes'
    | '/_authenticated/painel/kds'
    | '/_authenticated/painel/pagamentos'
    | '/_authenticated/painel/pdv'
    | '/_authenticated/painel/pedidos'
    | '/_authenticated/painel/personalizar'
    | '/_authenticated/painel/privacidade'
    | '/_authenticated/painel/produtos'
    | '/_authenticated/painel/promocoes'
    | '/_authenticated/painel/relatorios'
    | '/_authenticated/painel/salao'
    | '/_authenticated/painel/suporte'
    | '/_authenticated/painel/whatsapp'
    | '/api/v1/$'
    | '/_authenticated/painel/'
    | '/api/public/agenda/lembretes'
    | '/api/public/assinaturas/cobrancas'
    | '/api/public/assinaturas/pedidos'
    | '/api/public/carrinho/lembretes'
    | '/api/public/cashback/expiracao'
    | '/api/public/encomendas/lembretes'
    | '/api/public/evolution/$instanceKey'
    | '/api/public/integracoes/retentativas'
    | '/api/public/notificacoes/push'
    | '/api/public/pagamentos/$provider'
    | '/api/public/v1/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/api/public/integracoes/$kind/$storeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcompanharRoute: typeof AcompanharRoute
  AuthRoute: typeof AuthRoute
  CookiesRoute: typeof CookiesRoute
  MeusPedidosRoute: typeof MeusPedidosRoute
  PlanosRoute: typeof PlanosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  TermosRoute: typeof TermosRoute
  SlugAcompanharRoute: typeof SlugAcompanharRoute
  SlugCarrinhoRoute: typeof SlugCarrinhoRoute
  SlugCheckoutRoute: typeof SlugCheckoutRoute
  SlugMembrosRoute: typeof SlugMembrosRoute
  AgendamentoTokenRoute: typeof AgendamentoTokenRoute
  EncomendaTokenRoute: typeof EncomendaTokenRoute
  EntregaTokenRoute: typeof EntregaTokenRoute
  LojaSplatRoute: typeof LojaSplatRoute
  MesaTokenRoute: typeof MesaTokenRoute
  OrcamentoTokenRoute: typeof OrcamentoTokenRoute
  SlugIndexRoute: typeof SlugIndexRoute
  SlugCheckoutAgendamentoRoute: typeof SlugCheckoutAgendamentoRoute
  SlugCheckoutDigitalRoute: typeof SlugCheckoutDigitalRoute
  SlugCheckoutLojaRoute: typeof SlugCheckoutLojaRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiPublicAgendaLembretesRoute: typeof ApiPublicAgendaLembretesRoute
  ApiPublicAssinaturasCobrancasRoute: typeof ApiPublicAssinaturasCobrancasRoute
  ApiPublicAssinaturasPedidosRoute: typeof ApiPublicAssinaturasPedidosRoute
  ApiPublicCarrinhoLembretesRoute: typeof ApiPublicCarrinhoLembretesRoute
  ApiPublicCashbackExpiracaoRoute: typeof ApiPublicCashbackExpiracaoRoute
  ApiPublicEncomendasLembretesRoute: typeof ApiPublicEncomendasLembretesRoute
  ApiPublicEvolutionInstanceKeyRoute: typeof ApiPublicEvolutionInstanceKeyRoute
  ApiPublicIntegracoesRetentativasRoute: typeof ApiPublicIntegracoesRetentativasRoute
  ApiPublicNotificacoesPushRoute: typeof ApiPublicNotificacoesPushRoute
  ApiPublicPagamentosProviderRoute: typeof ApiPublicPagamentosProviderRoute
  ApiPublicV1SplatRoute: typeof ApiPublicV1SplatRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  ApiPublicIntegracoesKindStoreIdRoute: typeof ApiPublicIntegracoesKindStoreIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhar': {
      id: '/acompanhar'
      path: '/acompanhar'
      fullPath: '/acompanhar'
      preLoaderRoute: typeof AcompanharRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-pedidos': {
      id: '/meus-pedidos'
      path: '/meus-pedidos'
      fullPath: '/meus-pedidos'
      preLoaderRoute: typeof MeusPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/$slug'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/acompanhar': {
      id: '/$slug/acompanhar'
      path: '/$slug/acompanhar'
      fullPath: '/$slug/acompanhar'
      preLoaderRoute: typeof SlugAcompanharRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/carrinho': {
      id: '/$slug/carrinho'
      path: '/$slug/carrinho'
      fullPath: '/$slug/carrinho'
      preLoaderRoute: typeof SlugCarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/checkout': {
      id: '/$slug/checkout'
      path: '/$slug/checkout'
      fullPath: '/$slug/checkout'
      preLoaderRoute: typeof SlugCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/membros': {
      id: '/$slug/membros'
      path: '/$slug/membros'
      fullPath: '/$slug/membros'
      preLoaderRoute: typeof SlugMembrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/completar-cadastro': {
      id: '/_authenticated/completar-cadastro'
      path: '/completar-cadastro'
      fullPath: '/completar-cadastro'
      preLoaderRoute: typeof AuthenticatedCompletarCadastroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entregador': {
      id: '/_authenticated/entregador'
      path: '/entregador'
      fullPath: '/entregador'
      preLoaderRoute: typeof AuthenticatedEntregadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escolher-perfil': {
      id: '/_authenticated/escolher-perfil'
      path: '/escolher-perfil'
      fullPath: '/escolher-perfil'
      preLoaderRoute: typeof AuthenticatedEscolherPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/garcom': {
      id: '/_authenticated/garcom'
      path: '/garcom'
      fullPath: '/garcom'
      preLoaderRoute: typeof AuthenticatedGarcomRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kds': {
      id: '/_authenticated/kds'
      path: '/kds'
      fullPath: '/kds'
      preLoaderRoute: typeof AuthenticatedKdsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minha-conta': {
      id: '/_authenticated/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof AuthenticatedMinhaContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pdv': {
      id: '/_authenticated/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof AuthenticatedPdvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/agendamento/$token': {
      id: '/agendamento/$token'
      path: '/agendamento/$token'
      fullPath: '/agendamento/$token'
      preLoaderRoute: typeof AgendamentoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encomenda/$token': {
      id: '/encomenda/$token'
      path: '/encomenda/$token'
      fullPath: '/encomenda/$token'
      preLoaderRoute: typeof EncomendaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrega/$token': {
      id: '/entrega/$token'
      path: '/entrega/$token'
      fullPath: '/entrega/$token'
      preLoaderRoute: typeof EntregaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$': {
      id: '/loja/$'
      path: '/loja/$'
      fullPath: '/loja/$'
      preLoaderRoute: typeof LojaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesa/$token': {
      id: '/mesa/$token'
      path: '/mesa/$token'
      fullPath: '/mesa/$token'
      preLoaderRoute: typeof MesaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento/$token': {
      id: '/orcamento/$token'
      path: '/orcamento/$token'
      fullPath: '/orcamento/$token'
      preLoaderRoute: typeof OrcamentoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/checkout_/agendamento': {
      id: '/$slug/checkout_/agendamento'
      path: '/$slug/checkout/agendamento'
      fullPath: '/$slug/checkout/agendamento'
      preLoaderRoute: typeof SlugCheckoutAgendamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/checkout_/digital': {
      id: '/$slug/checkout_/digital'
      path: '/$slug/checkout/digital'
      fullPath: '/$slug/checkout/digital'
      preLoaderRoute: typeof SlugCheckoutDigitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/checkout_/loja': {
      id: '/$slug/checkout_/loja'
      path: '/$slug/checkout/loja'
      fullPath: '/$slug/checkout/loja'
      preLoaderRoute: typeof SlugCheckoutLojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/convite/$token': {
      id: '/_authenticated/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof AuthenticatedConviteTokenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entregador_/status': {
      id: '/_authenticated/entregador_/status'
      path: '/entregador/status'
      fullPath: '/entregador/status'
      preLoaderRoute: typeof AuthenticatedEntregadorStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/': {
      id: '/_authenticated/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof AuthenticatedPainelIndexRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/agendamentos': {
      id: '/_authenticated/painel/agendamentos'
      path: '/agendamentos'
      fullPath: '/painel/agendamentos'
      preLoaderRoute: typeof AuthenticatedPainelAgendamentosRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/assinatura': {
      id: '/_authenticated/painel/assinatura'
      path: '/assinatura'
      fullPath: '/painel/assinatura'
      preLoaderRoute: typeof AuthenticatedPainelAssinaturaRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/avaliacoes': {
      id: '/_authenticated/painel/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/painel/avaliacoes'
      preLoaderRoute: typeof AuthenticatedPainelAvaliacoesRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/clientes': {
      id: '/_authenticated/painel/clientes'
      path: '/clientes'
      fullPath: '/painel/clientes'
      preLoaderRoute: typeof AuthenticatedPainelClientesRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/cobrancas': {
      id: '/_authenticated/painel/cobrancas'
      path: '/cobrancas'
      fullPath: '/painel/cobrancas'
      preLoaderRoute: typeof AuthenticatedPainelCobrancasRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/configuracoes': {
      id: '/_authenticated/painel/configuracoes'
      path: '/configuracoes'
      fullPath: '/painel/configuracoes'
      preLoaderRoute: typeof AuthenticatedPainelConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/digitais': {
      id: '/_authenticated/painel/digitais'
      path: '/digitais'
      fullPath: '/painel/digitais'
      preLoaderRoute: typeof AuthenticatedPainelDigitaisRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/encomendas': {
      id: '/_authenticated/painel/encomendas'
      path: '/encomendas'
      fullPath: '/painel/encomendas'
      preLoaderRoute: typeof AuthenticatedPainelEncomendasRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/entregadores': {
      id: '/_authenticated/painel/entregadores'
      path: '/entregadores'
      fullPath: '/painel/entregadores'
      preLoaderRoute: typeof AuthenticatedPainelEntregadoresRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/entregas': {
      id: '/_authenticated/painel/entregas'
      path: '/entregas'
      fullPath: '/painel/entregas'
      preLoaderRoute: typeof AuthenticatedPainelEntregasRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/equipe': {
      id: '/_authenticated/painel/equipe'
      path: '/equipe'
      fullPath: '/painel/equipe'
      preLoaderRoute: typeof AuthenticatedPainelEquipeRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/estoque': {
      id: '/_authenticated/painel/estoque'
      path: '/estoque'
      fullPath: '/painel/estoque'
      preLoaderRoute: typeof AuthenticatedPainelEstoqueRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/fidelidade': {
      id: '/_authenticated/painel/fidelidade'
      path: '/fidelidade'
      fullPath: '/painel/fidelidade'
      preLoaderRoute: typeof AuthenticatedPainelFidelidadeRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/frete': {
      id: '/_authenticated/painel/frete'
      path: '/frete'
      fullPath: '/painel/frete'
      preLoaderRoute: typeof AuthenticatedPainelFreteRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/impressao': {
      id: '/_authenticated/painel/impressao'
      path: '/impressao'
      fullPath: '/painel/impressao'
      preLoaderRoute: typeof AuthenticatedPainelImpressaoRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/integracoes': {
      id: '/_authenticated/painel/integracoes'
      path: '/integracoes'
      fullPath: '/painel/integracoes'
      preLoaderRoute: typeof AuthenticatedPainelIntegracoesRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/kds': {
      id: '/_authenticated/painel/kds'
      path: '/kds'
      fullPath: '/painel/kds'
      preLoaderRoute: typeof AuthenticatedPainelKdsRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/pagamentos': {
      id: '/_authenticated/painel/pagamentos'
      path: '/pagamentos'
      fullPath: '/painel/pagamentos'
      preLoaderRoute: typeof AuthenticatedPainelPagamentosRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/pdv': {
      id: '/_authenticated/painel/pdv'
      path: '/pdv'
      fullPath: '/painel/pdv'
      preLoaderRoute: typeof AuthenticatedPainelPdvRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/pedidos': {
      id: '/_authenticated/painel/pedidos'
      path: '/pedidos'
      fullPath: '/painel/pedidos'
      preLoaderRoute: typeof AuthenticatedPainelPedidosRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/personalizar': {
      id: '/_authenticated/painel/personalizar'
      path: '/personalizar'
      fullPath: '/painel/personalizar'
      preLoaderRoute: typeof AuthenticatedPainelPersonalizarRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/privacidade': {
      id: '/_authenticated/painel/privacidade'
      path: '/privacidade'
      fullPath: '/painel/privacidade'
      preLoaderRoute: typeof AuthenticatedPainelPrivacidadeRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/produtos': {
      id: '/_authenticated/painel/produtos'
      path: '/produtos'
      fullPath: '/painel/produtos'
      preLoaderRoute: typeof AuthenticatedPainelProdutosRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/promocoes': {
      id: '/_authenticated/painel/promocoes'
      path: '/promocoes'
      fullPath: '/painel/promocoes'
      preLoaderRoute: typeof AuthenticatedPainelPromocoesRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/relatorios': {
      id: '/_authenticated/painel/relatorios'
      path: '/relatorios'
      fullPath: '/painel/relatorios'
      preLoaderRoute: typeof AuthenticatedPainelRelatoriosRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/salao': {
      id: '/_authenticated/painel/salao'
      path: '/salao'
      fullPath: '/painel/salao'
      preLoaderRoute: typeof AuthenticatedPainelSalaoRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/suporte': {
      id: '/_authenticated/painel/suporte'
      path: '/suporte'
      fullPath: '/painel/suporte'
      preLoaderRoute: typeof AuthenticatedPainelSuporteRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/whatsapp': {
      id: '/_authenticated/painel/whatsapp'
      path: '/whatsapp'
      fullPath: '/painel/whatsapp'
      preLoaderRoute: typeof AuthenticatedPainelWhatsappRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agenda/lembretes': {
      id: '/api/public/agenda/lembretes'
      path: '/api/public/agenda/lembretes'
      fullPath: '/api/public/agenda/lembretes'
      preLoaderRoute: typeof ApiPublicAgendaLembretesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/assinaturas/cobrancas': {
      id: '/api/public/assinaturas/cobrancas'
      path: '/api/public/assinaturas/cobrancas'
      fullPath: '/api/public/assinaturas/cobrancas'
      preLoaderRoute: typeof ApiPublicAssinaturasCobrancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/assinaturas/pedidos': {
      id: '/api/public/assinaturas/pedidos'
      path: '/api/public/assinaturas/pedidos'
      fullPath: '/api/public/assinaturas/pedidos'
      preLoaderRoute: typeof ApiPublicAssinaturasPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/carrinho/lembretes': {
      id: '/api/public/carrinho/lembretes'
      path: '/api/public/carrinho/lembretes'
      fullPath: '/api/public/carrinho/lembretes'
      preLoaderRoute: typeof ApiPublicCarrinhoLembretesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cashback/expiracao': {
      id: '/api/public/cashback/expiracao'
      path: '/api/public/cashback/expiracao'
      fullPath: '/api/public/cashback/expiracao'
      preLoaderRoute: typeof ApiPublicCashbackExpiracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/encomendas/lembretes': {
      id: '/api/public/encomendas/lembretes'
      path: '/api/public/encomendas/lembretes'
      fullPath: '/api/public/encomendas/lembretes'
      preLoaderRoute: typeof ApiPublicEncomendasLembretesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/evolution/$instanceKey': {
      id: '/api/public/evolution/$instanceKey'
      path: '/api/public/evolution/$instanceKey'
      fullPath: '/api/public/evolution/$instanceKey'
      preLoaderRoute: typeof ApiPublicEvolutionInstanceKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integracoes/retentativas': {
      id: '/api/public/integracoes/retentativas'
      path: '/api/public/integracoes/retentativas'
      fullPath: '/api/public/integracoes/retentativas'
      preLoaderRoute: typeof ApiPublicIntegracoesRetentativasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notificacoes/push': {
      id: '/api/public/notificacoes/push'
      path: '/api/public/notificacoes/push'
      fullPath: '/api/public/notificacoes/push'
      preLoaderRoute: typeof ApiPublicNotificacoesPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pagamentos/$provider': {
      id: '/api/public/pagamentos/$provider'
      path: '/api/public/pagamentos/$provider'
      fullPath: '/api/public/pagamentos/$provider'
      preLoaderRoute: typeof ApiPublicPagamentosProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/$': {
      id: '/api/public/v1/$'
      path: '/api/public/v1/$'
      fullPath: '/api/public/v1/$'
      preLoaderRoute: typeof ApiPublicV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integracoes/$kind/$storeId': {
      id: '/api/public/integracoes/$kind/$storeId'
      path: '/api/public/integracoes/$kind/$storeId'
      fullPath: '/api/public/integracoes/$kind/$storeId'
      preLoaderRoute: typeof ApiPublicIntegracoesKindStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedPainelRouteChildren {
  AuthenticatedPainelAgendamentosRoute: typeof AuthenticatedPainelAgendamentosRoute
  AuthenticatedPainelAssinaturaRoute: typeof AuthenticatedPainelAssinaturaRoute
  AuthenticatedPainelAvaliacoesRoute: typeof AuthenticatedPainelAvaliacoesRoute
  AuthenticatedPainelClientesRoute: typeof AuthenticatedPainelClientesRoute
  AuthenticatedPainelCobrancasRoute: typeof AuthenticatedPainelCobrancasRoute
  AuthenticatedPainelConfiguracoesRoute: typeof AuthenticatedPainelConfiguracoesRoute
  AuthenticatedPainelDigitaisRoute: typeof AuthenticatedPainelDigitaisRoute
  AuthenticatedPainelEncomendasRoute: typeof AuthenticatedPainelEncomendasRoute
  AuthenticatedPainelEntregadoresRoute: typeof AuthenticatedPainelEntregadoresRoute
  AuthenticatedPainelEntregasRoute: typeof AuthenticatedPainelEntregasRoute
  AuthenticatedPainelEquipeRoute: typeof AuthenticatedPainelEquipeRoute
  AuthenticatedPainelEstoqueRoute: typeof AuthenticatedPainelEstoqueRoute
  AuthenticatedPainelFidelidadeRoute: typeof AuthenticatedPainelFidelidadeRoute
  AuthenticatedPainelFreteRoute: typeof AuthenticatedPainelFreteRoute
  AuthenticatedPainelImpressaoRoute: typeof AuthenticatedPainelImpressaoRoute
  AuthenticatedPainelIntegracoesRoute: typeof AuthenticatedPainelIntegracoesRoute
  AuthenticatedPainelKdsRoute: typeof AuthenticatedPainelKdsRoute
  AuthenticatedPainelPagamentosRoute: typeof AuthenticatedPainelPagamentosRoute
  AuthenticatedPainelPdvRoute: typeof AuthenticatedPainelPdvRoute
  AuthenticatedPainelPedidosRoute: typeof AuthenticatedPainelPedidosRoute
  AuthenticatedPainelPersonalizarRoute: typeof AuthenticatedPainelPersonalizarRoute
  AuthenticatedPainelPrivacidadeRoute: typeof AuthenticatedPainelPrivacidadeRoute
  AuthenticatedPainelProdutosRoute: typeof AuthenticatedPainelProdutosRoute
  AuthenticatedPainelPromocoesRoute: typeof AuthenticatedPainelPromocoesRoute
  AuthenticatedPainelRelatoriosRoute: typeof AuthenticatedPainelRelatoriosRoute
  AuthenticatedPainelSalaoRoute: typeof AuthenticatedPainelSalaoRoute
  AuthenticatedPainelSuporteRoute: typeof AuthenticatedPainelSuporteRoute
  AuthenticatedPainelWhatsappRoute: typeof AuthenticatedPainelWhatsappRoute
  AuthenticatedPainelIndexRoute: typeof AuthenticatedPainelIndexRoute
}

const AuthenticatedPainelRouteChildren: AuthenticatedPainelRouteChildren = {
  AuthenticatedPainelAgendamentosRoute: AuthenticatedPainelAgendamentosRoute,
  AuthenticatedPainelAssinaturaRoute: AuthenticatedPainelAssinaturaRoute,
  AuthenticatedPainelAvaliacoesRoute: AuthenticatedPainelAvaliacoesRoute,
  AuthenticatedPainelClientesRoute: AuthenticatedPainelClientesRoute,
  AuthenticatedPainelCobrancasRoute: AuthenticatedPainelCobrancasRoute,
  AuthenticatedPainelConfiguracoesRoute: AuthenticatedPainelConfiguracoesRoute,
  AuthenticatedPainelDigitaisRoute: AuthenticatedPainelDigitaisRoute,
  AuthenticatedPainelEncomendasRoute: AuthenticatedPainelEncomendasRoute,
  AuthenticatedPainelEntregadoresRoute: AuthenticatedPainelEntregadoresRoute,
  AuthenticatedPainelEntregasRoute: AuthenticatedPainelEntregasRoute,
  AuthenticatedPainelEquipeRoute: AuthenticatedPainelEquipeRoute,
  AuthenticatedPainelEstoqueRoute: AuthenticatedPainelEstoqueRoute,
  AuthenticatedPainelFidelidadeRoute: AuthenticatedPainelFidelidadeRoute,
  AuthenticatedPainelFreteRoute: AuthenticatedPainelFreteRoute,
  AuthenticatedPainelImpressaoRoute: AuthenticatedPainelImpressaoRoute,
  AuthenticatedPainelIntegracoesRoute: AuthenticatedPainelIntegracoesRoute,
  AuthenticatedPainelKdsRoute: AuthenticatedPainelKdsRoute,
  AuthenticatedPainelPagamentosRoute: AuthenticatedPainelPagamentosRoute,
  AuthenticatedPainelPdvRoute: AuthenticatedPainelPdvRoute,
  AuthenticatedPainelPedidosRoute: AuthenticatedPainelPedidosRoute,
  AuthenticatedPainelPersonalizarRoute: AuthenticatedPainelPersonalizarRoute,
  AuthenticatedPainelPrivacidadeRoute: AuthenticatedPainelPrivacidadeRoute,
  AuthenticatedPainelProdutosRoute: AuthenticatedPainelProdutosRoute,
  AuthenticatedPainelPromocoesRoute: AuthenticatedPainelPromocoesRoute,
  AuthenticatedPainelRelatoriosRoute: AuthenticatedPainelRelatoriosRoute,
  AuthenticatedPainelSalaoRoute: AuthenticatedPainelSalaoRoute,
  AuthenticatedPainelSuporteRoute: AuthenticatedPainelSuporteRoute,
  AuthenticatedPainelWhatsappRoute: AuthenticatedPainelWhatsappRoute,
  AuthenticatedPainelIndexRoute: AuthenticatedPainelIndexRoute,
}

const AuthenticatedPainelRouteWithChildren =
  AuthenticatedPainelRoute._addFileChildren(AuthenticatedPainelRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCompletarCadastroRoute: typeof AuthenticatedCompletarCadastroRoute
  AuthenticatedEntregadorRoute: typeof AuthenticatedEntregadorRoute
  AuthenticatedEscolherPerfilRoute: typeof AuthenticatedEscolherPerfilRoute
  AuthenticatedGarcomRoute: typeof AuthenticatedGarcomRoute
  AuthenticatedKdsRoute: typeof AuthenticatedKdsRoute
  AuthenticatedMinhaContaRoute: typeof AuthenticatedMinhaContaRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRouteWithChildren
  AuthenticatedPdvRoute: typeof AuthenticatedPdvRoute
  AuthenticatedConviteTokenRoute: typeof AuthenticatedConviteTokenRoute
  AuthenticatedEntregadorStatusRoute: typeof AuthenticatedEntregadorStatusRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCompletarCadastroRoute: AuthenticatedCompletarCadastroRoute,
  AuthenticatedEntregadorRoute: AuthenticatedEntregadorRoute,
  AuthenticatedEscolherPerfilRoute: AuthenticatedEscolherPerfilRoute,
  AuthenticatedGarcomRoute: AuthenticatedGarcomRoute,
  AuthenticatedKdsRoute: AuthenticatedKdsRoute,
  AuthenticatedMinhaContaRoute: AuthenticatedMinhaContaRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRouteWithChildren,
  AuthenticatedPdvRoute: AuthenticatedPdvRoute,
  AuthenticatedConviteTokenRoute: AuthenticatedConviteTokenRoute,
  AuthenticatedEntregadorStatusRoute: AuthenticatedEntregadorStatusRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcompanharRoute: AcompanharRoute,
  AuthRoute: AuthRoute,
  CookiesRoute: CookiesRoute,
  MeusPedidosRoute: MeusPedidosRoute,
  PlanosRoute: PlanosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  TermosRoute: TermosRoute,
  SlugAcompanharRoute: SlugAcompanharRoute,
  SlugCarrinhoRoute: SlugCarrinhoRoute,
  SlugCheckoutRoute: SlugCheckoutRoute,
  SlugMembrosRoute: SlugMembrosRoute,
  AgendamentoTokenRoute: AgendamentoTokenRoute,
  EncomendaTokenRoute: EncomendaTokenRoute,
  EntregaTokenRoute: EntregaTokenRoute,
  LojaSplatRoute: LojaSplatRoute,
  MesaTokenRoute: MesaTokenRoute,
  OrcamentoTokenRoute: OrcamentoTokenRoute,
  SlugIndexRoute: SlugIndexRoute,
  SlugCheckoutAgendamentoRoute: SlugCheckoutAgendamentoRoute,
  SlugCheckoutDigitalRoute: SlugCheckoutDigitalRoute,
  SlugCheckoutLojaRoute: SlugCheckoutLojaRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiPublicAgendaLembretesRoute: ApiPublicAgendaLembretesRoute,
  ApiPublicAssinaturasCobrancasRoute: ApiPublicAssinaturasCobrancasRoute,
  ApiPublicAssinaturasPedidosRoute: ApiPublicAssinaturasPedidosRoute,
  ApiPublicCarrinhoLembretesRoute: ApiPublicCarrinhoLembretesRoute,
  ApiPublicCashbackExpiracaoRoute: ApiPublicCashbackExpiracaoRoute,
  ApiPublicEncomendasLembretesRoute: ApiPublicEncomendasLembretesRoute,
  ApiPublicEvolutionInstanceKeyRoute: ApiPublicEvolutionInstanceKeyRoute,
  ApiPublicIntegracoesRetentativasRoute: ApiPublicIntegracoesRetentativasRoute,
  ApiPublicNotificacoesPushRoute: ApiPublicNotificacoesPushRoute,
  ApiPublicPagamentosProviderRoute: ApiPublicPagamentosProviderRoute,
  ApiPublicV1SplatRoute: ApiPublicV1SplatRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  ApiPublicIntegracoesKindStoreIdRoute: ApiPublicIntegracoesKindStoreIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
