// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqqhjmikbbuhenmbdwol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxcWhqbWlrYmJ1aGVubWJkd29sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODgyNzg4MTEsImV4cCI6MjEwMzg1NDgxMX0.iUyoYjWiLIfxudS4JwW1gt2u716-qK0Vym2nq-8MFAY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});